#!/bin/sh

# Set these paths appropriately

BIN=/home/vamsi/project/nn/treeTagger/bin
CMD=/home/vamsi/project/nn/treeTagger/cmd
LIB=/home/vamsi/project/nn/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
