#!/bin/sh

# Set these paths appropriately

BIN=/home/vamsi/project/nn/treeTagger/bin
CMD=/home/vamsi/project/nn/treeTagger/cmd
LIB=/home/vamsi/project/nn/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
